### ISSUE TITLE
Outdated url

### ISSUE THREAD

**Issue by mesozoic-drones** [MobilityData/awesome-transit#160]
In README.md there is a link to "Muni, this moment" added by @luqmaan in commit d685fefb8d71491f468a33de87f97ecfba8ac7a9

Now it leads to the 18+ site =) 

I think it's better either to delete it or to update the url.

**Comment by barbeau** [comment]
@mesozoic-drones Thanks for flagging this! Looks like someone didn't renew a domain name. I removed it from the list as from some quick Googling I couldn't find a newer link to the original site.

If anyone knows an updated URL we can re-add it.
