### ISSUE TITLE
Citylines

### ISSUE THREAD

**Issue by BrunoSalerno** [MobilityData/awesome-transit#164]
Maybe it is interesting to add [citylines.co](https://www.citylines.co) to the list. It's a collaborative mapping platform for transit data, focused on the evolution of the networks. The data can be downloaded as GeoJSON from [citylines.co/data](https://www.citylines.co/data).
I can open a PR, but I'm not sure in which category should it go.

**Comment by barbeau** [comment]
Interesting! It should probably go in "Web apps" section, and we should create another subheading "Crowdsourced transit data" under the "Data" section for it (and OpenStreetMap should go there too). PR is welcome!
