### ISSUE TITLE
link to "How Transit integrates GTFS" docs

### ISSUE THREAD

**Issue by derhuerst** [MobilityData/awesome-transit#174]
The [*How Transit integrates GTFS*](https://resources.transit.app/article/329-how-transit-integrates-gtfs) may be Transit-specific, but IMO they serve as a great collection of best practices on top of the [GTFS Best Practices](https://developers.google.com/transit/gtfs/guides/best-practices) (which they also link to), so we could link to them here.

**Comment by barbeau** [comment]
@derhuerst Sounds good to me! Maybe add them under the existing GTFS Best Practices entry, with a clear indication that it's by Transit App? PRs welcome!
