### ISSUE TITLE
Tempus : OpenSource framework for multimodal routing

### ISSUE THREAD

**Issue by vpicavet** [MobilityData/awesome-transit#25]
Hi,

Not sure which category this belongs to.

Maybe you could integrate Tempus, which is an OpenSource framework for multimodal routing
More informations here : 

http://www.oslandia.com/new-version-of-tempus-a-framework-for-multimodal-route-planning-en.html
https://github.com/Ifsttar/Tempus
https://github.com/Mappy/Tempus/blob/mappy/doc/Documentation.md
https://vimeo.com/114875069

**Comment by luqmaan** [comment]
Maybe we need a new category? Any suggestions on what to cal it?

**Comment by vpicavet** [comment]
frameworks and server-side components ?

**Comment by luqmaan** [comment]
:thumbsup: Frameworks sounds good to me.

Want to submit a PR with and updated table of contents?

**Comment by barbeau** [comment]
IMHO "Frameworks" is a little too generic and abstract - everyone has a different definition.  Maybe "Software Libraries" instead?

We already have an "APIs" section - maybe we organize as follows:
- APIs - readily available REST APIs for transit data
- Software libraries - libraries that can be used in other transit applications

Some applications would fit into both - sounds like Tempus would be one of those.

**Comment by luqmaan** [comment]
Closing this issue. Please open a PR with the changes you'd like to make @vpicavet.
