### ISSUE TITLE
Add TransXchange convertors

### ISSUE THREAD

**Issue by barbeau** [MobilityData/awesome-transit#38]
See https://groups.google.com/forum/#!topic/transit-developers/TGJH-gBLYGA.  Creating this as a placeholder issue so I don't forget :).

**Comment by luqmaan** [comment]
Which links should we add?
- https://github.com/Transporter-Project/transxchange-to-gtfs
- https://github.com/jpf18/TransXChange2GTFS
- https://www.gov.uk/government/publications/transxchange-publisher

**Comment by barbeau** [comment]
I'd say all of the above.  Seems like there isn't a single winner at this point and they could all use work.
