### ISSUE TITLE
Move or change GTFS Data Exchange to Historical

### ISSUE THREAD

**Issue by themonki** [MobilityData/awesome-transit#43]
The site http://www.gtfs-data-exchange.com/ on the secction feed, according to what they have reported on them website, will not be updated feeds:

GTFS Data Exchange Shutting Down

Timeline for shutting down GTFS Data Exchange:

April 1, 2016 - Feed registry and file uploads disabled
May 1, 2016 - Automatic feed updates disabled
July 1, 2016 - API access to feeds disabled.
Sept 1, 2016 - GTFS-Data-Exchange will switch to a minimal index of agencies

**Comment by barbeau** [comment]
I'd vote for leaving it on the list, but clearly marking it as deprecated.  Access to historical data via S3 is still available.

**Comment by themonki** [comment]
Maby addition on section like "Historical feeds" because it continues to have a good list with different agencies.

**Comment by luqmaan** [comment]
I opened a PR to move gtfs-data-exchange.com down the list and update its description: #44.

Also, the data isn't easy to access:

> Q: What will happen to historical feeds on gtfs-data-exchange?
> A: Historic feed archive will be available for research via AWS S3 "requestor pays" policy. The dataset is currently 13k files totaling 93G from 2008 onward. Contact me if you'd like access.

I wonder if that data could be hosted on GitHub instead? To avoid having to pay, you could shard the data across multiple repos (by time/agency).

**Comment by barbeau** [comment]
What is the limit on Github repo sizes?

**Comment by luqmaan** [comment]
1GB https://help.github.com/articles/what-is-my-disk-quota/
