### ISSUE TITLE
GTFS libraries to add to the list

### ISSUE THREAD

**Issue by araichev** [MobilityData/awesome-transit#52]
I've used both of the following GTFS libraries extensively and think they are good to add to the list.
- [multigtfs](https://github.com/tulsawebdevs/django-multi-gtfs), a Django app to import and export GTSF
- [GTFSTK](https://github.com/araichev/gtfstk), a Python tool kit for processing GTFS

I confess that i'm the author of GTFSTK :-)

**Comment by luqmaan** [comment]
GTFSTK looks great.

Can you open a pull request that add multigtfs and GTFSTK them to the [GTFS Libraries](https://github.com/luqmaan/awesome-transit#gtfs-libraries) section?

**Comment by araichev** [comment]
Yep. Done.
