### ISSUE TITLE
ACTransit Open Source

### ISSUE THREAD

**Issue by actransitdevteam** [MobilityData/awesome-transit#54]
https://github.com/actransitorg is new open source software repository for AC Transit applications.  Currently, ACTransit.Training has been released.

http://camsys.software/products/transam
TransAM is an open-source asset management platform

**Comment by barbeau** [comment]
@actransitdevteam Congrats, that's great!

Could you please open a pull request adding TransAm to the main README?  I think it would probably fit best under "Agency Tools" - https://github.com/luqmaan/awesome-transit#agency-tools.

We aren't yet listing agency open-source respositories, but I think it would be great to start a new section for that.  Maybe under "Community", something like:

> ### Community
> 
> Places to ask questions and find other community resources.
> - [TransitWiki](http://transitwiki.org) - A community wiki for transit planners. Like this repo, but better.
> - [Transit Developers mailing list](https://groups.google.com/forum/#!forum/transit-developers)
> - OneBusAway
>   - [OneBusAway User mailing list](http://groups.google.com/group/onebusaway-users)
>   - [OneBusAway Developers mailing list](http://groups.google.com/group/onebusaway-developers)
>   - [OneBusAway API mailing list](http://groups.google.com/group/onebusaway-api)
>   - [OneBusAway Slack chat](https://onebusaway.herokuapp.com/)
> - Transit Agency Open-source Repositories
>   - [AC Transit](https://github.com/actransitorg)

**Comment by mpaine-act** [comment]
Should we clone this repository?  I see the outstanding two issues haven't been added (from april?)

**Comment by barbeau** [comment]
@mpaine-act The proper way to contribute to this repository is to fork it on Github, create a new branch, add your change as a new commit, and then open a pull request here with your changes.  You can see how other have done this in the past by looking at other pull requests that have been merged here - https://github.com/luqmaan/awesome-transit/pulls?q=is%3Apr+is%3Aclosed.

The issue from April is my own - I just haven't gotten around to putting it into a pull request format yet :).

**Comment by mpaine-act** [comment]
Will do. thanks,

**Comment by barbeau** [comment]
Thanks!  And actually, I believe Github now makes this process even simpler - if you go to the README in this repository and click the edit button, it will automatically take care of forking the repo, creating a new branch, and opening the pull request:

![image](https://cloud.githubusercontent.com/assets/928045/20022375/9906ec60-a2b0-11e6-93d1-7f6f73f0728b.png)

**Comment by barbeau** [comment]
@actransitdevteam Also, it's fine to leave this issue open until the pull request is closed/merged - issues are a good placeholder until the info actually gets merged.
