### ISSUE TITLE
Add Getting Started section

### ISSUE THREAD

**Issue by luqmaan** [MobilityData/awesome-transit#58]
Any thoughts on adding a beginners/introduction section?

---------

### Getting started

If this is your first time dealing with transit data, you might find these links useful:

- [GTFS](https://developers.google.com/transit/gtfs/) - GTFS is a of text files that contains infrequently changing transit data, like stops, routes, trips, and other schedule data. Most transit agencies typically update their GTFS feed every few months.
- [GTFS Realtime](https://developers.google.com/transit/gtfs-realtime/) - GTFS Realtime consists of three binary files that contain realtime vehicle positions, realtime arrival information, and service alerts. Transit agencies typically update these files every minute.
- [Transitland ](https://transit.land/) - A community curated list of GTFS/GTFS-realtime data feeds from around the world. If you're trying to get realtime data for some agency, this is a good place to start.

-------

Some other things we could add:

- Explain what OneBusAway is
- Mention some of the other common transit data formats like SIRI

**Comment by barbeau** [comment]
Yeah, that's a great idea. Reference to Transitwiki.Org GTFS page would be good to for non technical folks.
