### ISSUE TITLE
Add TIDES Project to the Data section

### ISSUE THREAD

**Issue by jlstpaul** [MobilityData/awesome-transit#72]
Would it be possible to add a link to the TIDES Project (https://groups.google.com/forum/#!forum/tidesproject) to the Data section.  

TIDES is the Transit ITS Data Exchange Specification and is an effort to create standard data structures, APIs, and data management tools for historical transit ITS data including AVL, APC and AFC Data.  

Note: I apologize if this request does not follow the correct standards.  I am a git-newbie.

Submitted by: John Levin

**Comment by barbeau** [comment]
Sure!  Is there any documentation online that we could link to directly, in place of the Google Group?

If not, the group will do.

In the future feel free to propose a change to the main README via a Github pull request - this makes it easier (and faster) for us to merge changes.  More info at https://help.github.com/articles/creating-a-pull-request/.

**Comment by jlstpaul** [comment]
Thanks.  There are a few older docs on Google Drive, but I have moved most of them to the Google Group for the time being.  There is not another online resource at this point.  When one I created, I’ll be sure to pin the link to the top of the Google Group.

Thanks for the directions on the pull request.

John

**Comment by barbeau** [comment]
Ok, just added it - please check it out and let me know if you want to tweak the wording at all:
https://github.com/luqmaan/awesome-transit#data

**Comment by jlstpaul** [comment]
Looks great.  Thank you!!
