### ISSUE TITLE
GTFS Crowdsourcing Concept App

### ISSUE THREAD

**Issue by tdurand** [MobilityData/awesome-transit#83]
Maybe it would be interesting to add this project by moovel lab: http://lab.moovel.com/projects/gtfs-edtr

**Comment by barbeau** [comment]
@tdurand Sorry for the delayed response!  Thanks for sharing this. Do you know if the source code for that project is hosted on Github?  I poked around, including Moovel's Github page, but couldn't find it.  There don't seem to be any links in the article itself, unless I missed them.

**Comment by tdurand** [comment]
I think it is just a design concept, no code was written 😉 , maybe it won't be as relevant for your list then

**Comment by barbeau** [comment]
@tdurand Ok, thanks.  Yes, I'm going to close this for now, but if we're able to identify any apps or code that came out of this I can re-open and add to the list.
