### ISSUE TITLE
Add TransitClock

### ISSUE THREAD

**Issue by radumas** [MobilityData/awesome-transit#91]
I don't entirely know the history of Transitime vs. TransitClock. But this list is missing a reference to the latter.

(I also don't fully understand the full capabilities of the Transit Clock so not 100% certain how/where to list it)

**Comment by barbeau** [comment]
Thanks for opening this!  I just updated the list - Swiftly is stepping away from the open-source Transitime project, which is being rebranded as "The Transit Clock" to avoid confusion with Swiftly's proprietary product (that is NOT open-source).  Home page at https://thetransitclock.org/.
