### ISSUE TITLE
Add gtfspy to the list

### ISSUE THREAD

**Issue by rmkujala** [MobilityData/awesome-transit#92]
We have been developing a Python package for GTFS-based public transport network analyses.
For more information, please see here: https://github.com/CxAalto/gtfspy (see also https://github.com/CxAalto/gtfspy-webviz).

Would be great if our package would be added to this list. 
If deemed suitable, I can make a pull request.

**Comment by barbeau** [comment]
Looks cool @rmkujala!  I'd like to add it to the list, so please open a PR.

For categories, seems like `gtfspy` would best fit under https://github.com/CUTR-at-USF/awesome-transit#gtfs-libraries, and `gtfspy-webviz` would best fit under https://github.com/CUTR-at-USF/awesome-transit#visualizations, but let me know if you think differently.  In the description be sure to cross-link them so it's easy to tell that the two projects relate.
