### ISSUE TITLE
`Gtfs Data Manager` is deprecated

### ISSUE THREAD

**Issue by radumas** [MobilityData/awesome-transit#94]
Per [the repository](https://github.com/conveyal/gtfs-data-manager)
>GTFS workflow tool **This project is DEPRECATED, see conveyal/datatools-manager for current version.** https://github.com/conveyal/datatools-manager

From the link there it seems the development version is now at https://github.com/catalogueglobal/datatools-ui
Quote from the [documentation](https://conveyal-data-tools.readthedocs.io/en/latest/)
>The Conveyal Transit Data Tools suite provides web-based tools for creating, managing, evaluating, and publishing transit data, specifically data stored in the General Transit Feed Specification (GTFS) format.

**Comment by barbeau** [comment]
Thanks for the heads up @radumas!

@landonreed I'd like to update the link to what was previously "GTFS Data Manager" - looks like that is deprecated, and now "Data Tools UI" is the new version - https://github.com/conveyal/datatools-ui.

However, that project says that "DEVELOPMENT NOW HAPPENING ON FORK AT: https://github.com/catalogueglobal/datatools-ui"

Which is the best repo to link to, the conveyal/datatools-ui, or catalogueglobal/datatools-ui?

**Comment by landonreed** [comment]
Hi, @barbeau.  I think we should just link to catalogueglobal/datatools-ui for now to minimize confusion.  If active development moves to the conveyal repo, we can update as needed.

Thanks for catching this, @radumas!

**Comment by barbeau** [comment]
So, if I'm going to be consistent here (see https://github.com/CUTR-at-USF/awesome-transit/pull/88), I think there needs to be a little more clarity of why the fork exists in the README of the conveyal repo - i.e., a pointer to the catalogueglobal repo.  Also, in the README of the catalogueglobal repo, it still hyperlinks back to the conveyal repos for the datatools-server and docs.

I've been trying to keep this list clean and easily understandable by developers by pointing only to master repositories and not forks, unless the fork and master are clearly documented and there is a good reason that both exist.  I don't want to erroneously point developers to a fork to have them build something on top of that, just to find out that the master repo had the most recent code, or vice versa.

@landonreed Would you be willing to clarify the relationship in the READMEs and fix the links as well to make it clear what is happening where?

**Comment by abyrd** [comment]
Hi @barbeau, we have a long-running partnership with some other organizations to help them develop the Catalogue platform, so to keep things simple we were all working on their fork. Since all our effort was concentrated there, it is now quite far ahead of Conveyal's original repo. However, Conveyal still develops and provides our Data Tools product, and within the next couple of months when our involvement in Catalogue winds down, we'll merge that fork back into the original repo. 

So: for the time being, the fork contains the current generation of the software. But soon, we will shift our attention back to the original repo.

**Comment by landonreed** [comment]
@barbeau, Conveyal is now working on the Data Tools application in the original repositories (conveyal/datatools-ui and conveyal/datatools-server). We can replace the GTFS Data Manager links with these if you haven't already done so. Or if it's helpful, I could submit a PR.

Thanks!

**Comment by barbeau** [comment]
@landonreed PR would be great, thanks!
