### ISSUE TITLE
Add hafas2gtfs

### ISSUE THREAD

**Issue by barbeau** [MobilityData/awesome-transit#99]
There are two hafas2gtfs projects:
* root - https://github.com/stefanw/hafas2gtfs
* fork - https://github.com/geops/hafas2gtfs

@stefanw I'd like to add the hafas2gtfs project to this list, but we have a policy against adding forks of projects unless the root project is clearly documented in the README as deprecated, or there's another well documented reason why both repositories exist.  It appears that the geops repository is now the main development repository, as it's almost a year ahead of the stefanw one. Would you be willing to update the READMEs for the above project(s) so it's clear to developers what the relationship is between the two projects?

**Comment by stefanw** [comment]
Done: https://github.com/stefanw/hafas2gtfs

For me this was just a one-off script at a hack day years ago. Please do something useful with it!

**Comment by barbeau** [comment]
Awesome, thanks @stefanw!  I just added it to the list in https://github.com/CUTR-at-USF/awesome-transit/commit/f69bf532382d5bffd451dab060f6b3c0b7317453.
